### ISSUE TITLE
Node self connections

### ISSUE THREAD

**Issue by catena2w** [ScorexFoundation/Scorex#185]
I started 2 nodes in ergo, logs of node binded to `127.0.0.1` contains
```
[ergoref-akka.actor.default-dispatcher-14] >> [INFO ] s.core.network.PeerConnectionHandler >> 12:51:00.041 Send message MessageSpec(65: Sync) to localhost/127.0.0.1:49928
[ergoref-akka.actor.default-dispatcher-16] >> [INFO ] s.core.network.PeerConnectionHandler >> 12:51:00.041 Send message MessageSpec(65: Sync) to localhost/127.0.0.1:9001
[ergoref-akka.actor.default-dispatcher-13] >> [INFO ] s.core.network.PeerConnectionHandler >> 12:51:00.041 Send message MessageSpec(65: Sync) to localhost/127.0.0.1:49922
[ergoref-akka.actor.default-dispatcher-16] >> [INFO ] s.core.network.PeerConnectionHandler >> 12:51:00.041 Received message MessageSpec(65: Sync) from localhost/127.0.0.1:49928
[ergoref-akka.actor.default-dispatcher-14] >> [INFO ] s.core.network.PeerConnectionHandler >> 12:51:00.041 Received message MessageSpec(65: Sync) from localhost/127.0.0.1:9001
```

Looks like problem is that it contain itself in settings in knownPeers section

**Comment by ceilican** [comment]
I wonder if this bug could have been introduced in the recent refactoring of `knownPeers` (https://github.com/ScorexFoundation/Scorex/pull/165) by @greenhat . I will have a closer look tomorrow. Maybe it could be due to my earlier removal of node nonce.

@catena2w, this is a new behaviour, right? Or could it have been happening before already?

@catena2w , are you sure that you started only 2 nodes? I see three different ports in the log messages that you shared...

**Comment by greenhat** [comment]
@catena2w `PeerManager` loads peers from `settings.knownPeers` without any check ( see - https://github.com/ScorexFoundation/Scorex/blob/ffa9c8b3e7b18ec6eebe0128beab654451077ec7/src/main/scala/scorex/core/network/peer/PeerManager.scala#L36 )
It'd probably be a good idea to not allow "self" address loaded from `settings.knownPeers`.

**Comment by catena2w** [comment]
@ceilican I'm sure there were just 2 nodes, but akka use different ports to open connections.
I think @greenhat is correct and this behaviour is related to `knownPeers` setting, however I wonder why there are 3 (!) connections to self at the same time in example above

**Comment by ceilican** [comment]
@catena2w @greenhat I have just created a PR (#190) with the change suggested by @greenhat. (Thanks, @greenhat!).

However, if we accept this PR, then I think we will be unable to run a few peers locally, on the same network address. In particular, I think the TwinsCoin example included in Scorex will not work anymore, because there all "settingsX.conf" files list known peers that have the same network address.

I think the behaviour that we currently have (before my PR) is:
1. If a node receives a new peer from somewhere else and this peer has the same network address as the node itself, we don't add this peer to the database (cf. line 50 in PeerManager).
2. However, if a peer having the same network address is being added because it was declared as a known peer in "settings.conf", we do add the peer, because this allows us to run many peers in the same address, at least for testing.

The behaviour above is probably better than the behaviour after the PR, which prevents item 2 above.

Therefore, I think this PR should be rejected. The issue in Ergo could be solved by simply not listing other local peers in "settings.conf".

@catena2w , what do you think?

**Comment by ceilican** [comment]
Actually, maybe I'm confusing things a bit... Sorry. In my comment above, I was wrongly thinking that the `bindAddress` and `declaredAddress` did not include the port. But they actually do. So, even when we have multiple peers running locally, they should have different ports and therefore be considered different from each other. So, please disregard my previous comment. I think we can accept the PR.

**Comment by ceilican** [comment]
@catena2w , could you share the `application.conf` files of the two nodes that you executed? Are they the files that can be found in the `node1` and `node2` folders here (https://github.com/ergoplatform/ergo/tree/master/src/main/resources)?

> I started 2 nodes in ergo, logs of node binded to `127.0.0.1` contains

Could you also tell me the port of the node that produced those log messages?
